### ISSUE TITLE
There is a slight discrepancy between the content of the paper and the code.

### ISSUE THREAD

**Issue by githubdemima123456** [SUwonglab/CausalEGM#5]
In Section 3.2, "Problem Setup and Notation," the variable Y is determined by the random variable Z1 and others, but in the corresponding code, the variable Y is determined by the random variable Z2 and others, and theoretically, it is also determined by Z2.

**Comment by kimmo1019** [comment]
Thanks for your feedback, you are right. (Z1, Z2) in the paper corresponds to (Z2, Z1) in the code. Will fix it in the next update

**Comment by kimmo1019** [comment]
For all users, this won't affect too much. Since the dimensions of Z1 and Z2 is somewhat random, no theoretical guidance so far. In most of the experiments in our CausalEGM paper, Z1 Z2 have the same dimension. Our current new work is trying to mitigate this problem by more theoretical analysis.

**Comment by kimmo1019** [comment]
@githubdemima123456 Hi, please find the latest release v0.4.0, which solves the discrepancy between paper and code.
